name: Run Miri
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Test with Miri
        env:
          RUSTFLAGS: "-C target-cpu=native"
        run: cargo miri nextest run --all