name: Run Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    environment: dev
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      # - name: Install cargo-llvm-cov
      #   uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Check CFAVML core builds no STD
        run: cargo build -p cfavml --no-default-features
      - name: Test system - Stable
        run:  cargo nextest run --all --nocapture
      - name: Test system - Nightly
        run:  cargo +nightly nextest run --all --nocapture --features nightly